# @package _global_

defaults:
  - launcher: local
  - job
  - dataset: 2d #celeba, 2d, stackedmnist
  - model: Basic #Basic, UNET
  - override hydra/launcher: submitit_slurm
  - _self_
  

# data
data_dir: ./data/

# logging
LOGGER: CSV # NEPTUNE, CSV, NONE
CSV_log_dir: ./

cache_gpu: False
num_cache_batches: 1
cache_refresh_stride: 100
plot_level: 1
mean_match: True
paths: 
  experiments_dir_name: experiments

# checkpoint
checkpoint_run: False
checkpoint_it: 13
checkpoint_pass: backward
sample_checkpoint_f: ""
sample_checkpoint_b: ""
checkpoint_f: ""
checkpoint_b: ""

hydra:
  launcher:
    partition: long
    cpus_per_task: 4
    mem_gb: 10
    gres: gpu:1
    timeout_min: 600
    additional_parameters:
      mail-user: alexander.tong@mila.quebec
      mail-type: END,FAIL
    setup: 
      - "module purge"
      - "module load miniconda/3 pytorch/1.8.1"
      - "conda activate bridge_test"
